# Generated by Django 5.0.1 on 2024-02-02 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_menu', models.CharField(max_length=100, verbose_name='Наименование')),
                ('url_menu', models.CharField(max_length=100, verbose_name='URL')),
                ('mother_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menutree.menu', verbose_name='Родительское меню')),
            ],
        ),
    ]
