# Generated by Django 5.0.1 on 2024-02-02 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menutree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='mother_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menutree.menu', verbose_name='Родительское меню'),
        ),
    ]
